name = "RouteSlopeDistance"
uuid = "07025e9e-5a27-4179-b043-88080b1ee239"
version = "0.4.0"
authors = ["hustf <hustf@users.noreply.github.com> and contributors"]

[deps]
BSplines = "488c2830-172b-11e9-1591-253b8a7df96d"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
GR_jll = "d2c73de3-f751-5644-a686-071e5b155ba9"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
IniFile = "83e8ac13-25f8-5344-8a64-a9f2b223428f"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
Smoothers = "012d725f-b4dd-4916-8440-03955fc52575"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[weakdeps]
Pango_jll = "36c8627f-9965-5494-a995-c6b170f724f3"

[compat]
GR_jll = "0.73.19"
LinearAlgebra = "1.12.0"
Plots = "1.41.3"
Printf = "1.11.0"
julia = "1.9"
